ALTER TABLE booking
    ALTER COLUMN booking_start TYPE timestamptz,
    ALTER COLUMN booking_end TYPE TIMESTAMPTZ,
    ALTER COLUMN created_at TYPE TIMESTAMPTZ;

ALTER TABLE station
    ALTER COLUMN created_at TYPE TIMESTAMPTZ;

ALTER TABLE session
    ALTER COLUMN start_time TYPE TIMESTAMPTZ,
    ALTER COLUMN end_time TYPE TIMESTAMPTZ,
    ALTER COLUMN created_at TYPE TIMESTAMPTZ;

ALTER TABLE console
      ALTER COLUMN created_at TYPE TIMESTAMPTZ;

ALTER TABLE users
    ALTER COLUMN created_at TYPE TIMESTAMPTZ,
    ALTER COLUMN updated_at TYPE TIMESTAMPTZ;